### ISSUE TITLE
feeder please ban him

### ISSUE THREAD

**Issue by theraw** [ark120202/aabs#346]
hello
i don't know if this is the right place to report this if not please tell me where i can report

**`account id : 83983056`** (i don't know how to find steam link i found this from "friend id" in game profile)

this user feeds the other team also sending the courier to get killd, when i asked him "why are you doing this?"

he said "my friend is host in other team" 

**`match id : 4113007687`**

i tried to ask him to get his friend name but didn't got it!

please take care, thank you.

**Comment by shimaosu** [comment]
Report in discord RomaBS#5411
