### ISSUE TITLE
Morphling - makes you lose atk bug or not?

### ISSUE THREAD

**Issue by theraw** [ark120202/aabs#351]
If you have lotus and morp no and he tries to be you then you will be turned into a morphling which also makes you lose all ATK dmg but not strength (not sure about strength) but i'm sure for atk, how is that possible i've seen him ruining games just because of this (in ranked)

**Comment by theraw** [comment]
please close if duplicate

**Comment by ark120202** [comment]
ea0e99f6d75848924ba947f249e29e9b712a7a2d

**Comment by theraw** [comment]
@ark120202 i suggest to do something about grimstroke to increase his cooldown, this hero at level 10-16 can handle you in silence time forever, i mean there is no cooldown, with a hero like zues or invoker you are unable to do something you can't use your magic!

i know that there is a talent which decreases cooldown and it will go in same point again but that's not a problem because you also have a high level and items and can manage to do something but by default levels he just keeps you in silence.. it doesn't look ok for me
