### ISSUE TITLE
Armor

### ISSUE THREAD

**Issue by AlexFack** [ark120202/aabs#369]
Я предлагаю сделать так, чтобы ловкость давала больше брони за единицу "ловким" героям для лучшего баланса героев атрибута "Сила" и "Ловкость". Механика брони работает так, что каждая ее единица увеличивает кол-во эффективного к физическому урону здоровья примерно на 6%. Я сделал некоторые подсчеты.
Возьмем двух героев. У первого будет 1000 силы и 100 ловкости и осн. атрибут "Сила", у второго -- 100 силы и 1000 ловкости с осн. атрибутом "Ловкость". Известно, что 1 ед. силы дает 20 ед. здоровья, а 1 ед. ловкости -- 0.14 ед. брони.
1000 силы дает герою чистыми 20000 ед. здоровья, в то время как 100 силы -- 2000 ед. 1000 ловкости дает герою 140 (140 * 6 = 840% увеличения эф. здоровья) брони, в то время как 100 ед. -- 14 (14 * 6 = 84% увеличения эф. здоровья). Подсчитаем кол-во эффективного здоровья для обоих персонажей: 20000 * 1.84 и 2000 * 8.4. Получается 36 800 ед. эф. для героя с основным атрибутом «Сила», и 16 800 ед. для героя с основным атрибутов «Ловкость». Разница более чем в два раза. Итак, что я предлагаю: поднять кол-во брони за ед. ловкости в два раза для героев с основным атрибутом "Ловкость". Т. е. ловкость им будет давать не 140 ед. брони за 1000 ед,, а 280 ед. Подставим эти цифры в расчеты: 20000 * 1.84 и 2000 * 16.8 (х2) (36 800 и 33 500). Так будет более честно. Чтобы изменения не сильно сказались на балансе в начале игры, героем с атрибутом "Ловкость" можно уменьшить кол-во базовой брони (не зависящей от ловкости) в два раза, а также увеличить скорость атаки для героев атрибута "Силы" для сбалансированного фарма. Учтя, что чистый урон от Haganemushi (мог написать неправильно) и Piercing Blade зависит от наносимого героем физического, это повлияет на баланс, сравняв оба класса персонажей. 
Если есть вопросы, пишите в ВК (https://vk.com/abd9bd9).

**Comment by ark120202** [comment]
Rejected by @MurzikViskas
