### ISSUE TITLE
Pure damage from Piercing and Haganemushi...

### ISSUE THREAD

**Issue by AlexFack** [ark120202/aabs#375]
Предлагаю пересмотреть концепт предметов, превращающих часть физического урона героя в чистый (хагиеша и пирсинг). Предметы ломают концепт брони как таковой и не позволяют нормально играть ловкачам, позволяя силовикам тупо их шотать. Как аналог урона, игнорирующего броню, уже есть сплеш, который реализуется не просто райткликом по ебалу и контрится правильной позиционкой. Эффект пирсинга и хагиеши можно заменить на, скажем, увеличение наносимого физического урона, как от ульта медузы, чтобы компенсировать этим длительность битв в глубоком лейте. А вот на сколько будет увеличиваться урон – вопрос открытый. Учтя, что сила дает 20 ед. хп, а единица брони дополнительно увеличивает его на 6%...  Скажем, х10 физического урона на хагиеше и х5 или х2.5 на пирсинге и ТОЛЬКО по героям. Таким образом, даже без механики чистого урона битвы будут динамичными, а не тупо райтклик друг в друга секунд тридцать, как в реборне в свое время, и ловкачи в лейте будут более чем играбельны. Пусть для этого и придется пожертвовать такой старой механикой, хоть и изначально не совсем правильной и честной.

Think about this, man.

**Comment by ark120202** [comment]
Rejected by @MurzikViskas
