### ISSUE TITLE
freya suggestion

### ISSUE THREAD

**Issue by theraw** [ark120202/aabs#394]
at this time freya is forgotten, to the ppl who play how long has been since you've seen freya carry? 

So my suggestion is make it same as tusk, freya ulti 350% crit dmg, tusk punch 350% crit dmg (this is how it is right now)

but tusk has a 10-15% punch chance at last talent.

So the suggestion is to add 10-15% freya auto "ulti" chance - talent!

**Comment by theraw** [comment]
also i suggest earthshaker "Enchant Totem" (800% +dmg) to get a reduce there's no way you can win vs a es in AABS.

**Comment by OneDiamondOne** [comment]
No, freya ulti very strong in 6 vs 6 , cos freya have bonus damage from
strength

**Comment by theraw** [comment]
@OneDiamondOne it's been very strong now isn't, 350% extra dmg is nothing is same as tusk punch 350% extra dmg.
