### ISSUE TITLE
Crystal maiden ultimate turns her invisible(to the player who is playing CM) with aghanim's septer

### ISSUE THREAD

**Issue by Mightykitten** [ark120202/aabs#406]
Crystal maiden ultimate turns her invisible(to the player who is playing CM) with aghanim's septer

**Comment by ark120202** [comment]
Couldn't reproduce, needs more details.

Do you have an arcana?

**Comment by Mightykitten** [comment]
No, i did without the aghanim's septer as well - i'll see if i can do it again

**Comment by Mightykitten** [comment]
I think it's either when CM dies 

https://gyazo.com/3e4e9e9c41ba116bcf96826f6b6d1f24

**Comment by ghost** [comment]
Тут все проще.
При репике на цмку и последующей смерти на ней, она просто пропадает

**Comment by ark120202** [comment]
CM disappearing after respawn is a known bug, that was fixed. Might be a regression from d99b565ea5829a32ca2e1d354bc559557a0462a7.
