### ISSUE TITLE
Имба герои

### ISSUE THREAD

**Issue by OneDiamondOne** [ark120202/aabs#411]
Зомби, ульта дамажит магическим уроном в процентах от текущего хп( даже по боссам) , растёт от усиления способностей; Дазл, дота ульта, качается в 3 скилл поинта до 18 уровня, снижает кд на предметы и заклинания на 50%!!! накладывает минус армор за каждый скилл , стаки ульты стакаются даже на боссах

**Comment by shimaosu** [comment]
Everything fxed in #409
