### ISSUE TITLE
7.20 abilities bugs ( Рома сказал так назвать)

### ISSUE THREAD

**Issue by OneDiamondOne** [ark120202/aabs#413]
У бистмастера звери качаются в 4 скилпоинта , у брюмастера пиво(2-й скилл) качается в 4 скилпоинта , ульта качается в 3 скилпоинта
хускар , 1-й скил качается в 4 скилпоинта , волки люкана качаются в 4 скилпоинта , бара 2-й скил(бульдоз) качается в 4 скилпоинта , туск 3-й скил качается в 4 скилпоинта, томба андаинга качается в 4 скилпоинта , антимаг 3-й скил качается в 4 скилпоинта , клинкз ульта качается в 3 скилпоинта , лон друид 2-й скил качается в 4 скилпоинта , мипо 3-й скил качается в 4 скилпоинта, 
пангольер 3-й скил качается в 4 скилпоинта , веник змейки(3-й скил) прокачиваются в 4 скилпоинта , чен 2-й скил качается в 4 скил поинта , дазл ульта качается в 3 скилпоинта, ейдолоны енигмы качаются в 4 скилпоинта , пеньки фуры качаются в 4 скилпоинта , ульта котла качается в 3 скилпоинта , 2-й лича качается в 4 скилпоинта , 3-й ОД качается в 4 скилпоинта , пугна 3-й скил качается в 4 скилпоинта , 3-й рубика качается в 4 скилпоинта , змейки шамана качаются в 4 скилпоинта , птички визажа качаются в 3 скилпоинта , голем варлока качается в 3 скилпоинта.

**Comment by ark120202** [comment]
Такое в личку Роме. Ну и большая часть, например

> волки люкана качаются в 4 скилпоинта

специально.
