### ISSUE TITLE
Ban /autokick Player in ranked games with  50-0 MMR 

### ISSUE THREAD

**Issue by shisha2563** [ark120202/aabs#455]
Hallo guys i saw it now time and time again. Player  with low MMR in my or enemy team that just feed at the start and then start to go afk/leave. and lucky some one else is in the team and get the most kills of him. if that guy is in my team with higher MMR and the Idiot with 0 MMR too the 0 MMR acc just goes afk/ leave the game,  without feeding.... soo can think about anything to ban / kick this acc give them Freez time to only play noranked games for the next 10 wins something like this :))))

**Comment by ark120202** [comment]
We're planning to implement something like this in 2.0.

As for now we can consider banning some players on per-case basis. You can report it to `@Мурзик Вискас#8593` on our [discord server](https://discord.gg/ERMXXPu).
