### ISSUE TITLE
Баги, краши и механики 

### ISSUE THREAD

**Issue by ghost** [ark120202/aabs#458]
- [x] Огр задержка на мульткаст и в сочетании с рефрешером можно происпользовать итемы столько раз сколько был множитель на рефрешере, в сочитании с мидасом мультикастом можно хоть всех на дуэле пере мидасить через призваных юнитов.
- [ ] Манта переводит основной атрибут в ловкость( Силовик с кучей силы его манта имеет кучу ловкасти)
- [x] Краш феникс+огр. Огр кидает мультикаст на феникса тот юзает sanray и если сработал мульткаст то по окончанию скила произойдет краш.

**Comment by ark120202** [comment]
2 - не смог повторить. Нужен отдельный issue с деталями.
