### ISSUE TITLE
agility lowers armor

### ISSUE THREAD

**Issue by DeathzTheAwesome** [ark120202/aabs#473]
After the most recent patch on dota agility now lowers your armor in this game mode ... each point of agility lowers armor by 0.04 this can be really annoying for agility hero's because it forces them to buy int to keep there armor up or they will have massive negative armor and be at ( -99% psychical resistance ) now you don't need as much int because each point of int rises armor by 0.1 but that is still just to break even you need 40% of what u have in agility in int to be at 0 armor. please fix this ... thanks

P.S. NERF SARA

**Comment by ark120202** [comment]
Looks like it's fixed
