### ISSUE TITLE
ВАР3 АРЕНА

### ISSUE THREAD

**Issue by NeVajN0** [ark120202/aabs#52]
Как начинается дуэль, нужно сделать что бы все появлялись там (без бафов!)
- Типа дум съел крипа и у него овер 900000000000 хп!Тоже самое про клинкза!
- Убрать РОСТ КРИПОВ из за того что криппы растут в РАЗМЕРЕ нету возможности направить нормально скил на героя!Потому что крип на весь экран!
- Сделать крипов не жирными а наоборот увелить им БРОНЮ и СОПРОТИВЛЯЕМОСТЬ!Так же добавить крипам скилы, БАШИ, увороты, типа как на БАБОЧКЕ УЛУЧШЕНОЙ, Потому что крипы имея 100 000хп дают нереальный бафф клинкзу и думу!
- Уменьшить стоимость крипов!За 20 минут безпрерывного фарма крипы дают почти 20к золота то есть ща 3 крипа ты покупаешь 2 книги на + 100 к стату (твоему). Либо сделать что бы книги были не по +100 (самые дорогие) а по + 20 и тд!Некоторые герое не имеют возможности фармить так же хорошо как (клинкз, дум, Вк, и тд)
ПЫ.СЫ!
Вообще главное это крипы и их ХП (это надо резать)пусть у них будет 1000 хп но овер много брони и сопротивляемости, что бы даже с 10к урона герой снимал максимум 20-15 от ХП крипка!
Это немного уладит проблему с имба героями!
Удачи!

**Comment by ark120202** [comment]
Covered by #42.
