### ISSUE TITLE
вытекают глаза от МОЛНИЙ

### ISSUE THREAD

**Issue by NeVajN0** [ark120202/aabs#54]
Просто ужас , эти молнии, эти вспышки (которые никак не выключаются)
Если выкручен графоний то пиздец, глаза просто стекают по щекам и капают на стол!
Я не знаю на кой хуй ты добавил это! (ладно если бы оно выключалось) АГа но хуй там!
Тебе абсолютно по хуй...и это прискорбно! ТАк как это ужасно дискомфортно!

**Comment by Alastor029711** [comment]
у нас все нормально, в чем проблема незнаю
