### ISSUE TITLE
VOID

### ISSUE THREAD

**Issue by NeVajN0** [ark120202/aabs#57]
Воид юзлес гавно!
Шанс баша 8% - серьезно??
Кд ульты 128 с екунд  - серьезно?
Нету ни одного профильного таланта - серьезно??
Ты малолетка обиженная - тебе говорят по факту в чем ты обосрался (а ты обижаешься и банишь людей)
Хз , прокомментируй такое решение, почему одни герои переапанные (обычные типа , ДК, ОМНИ, АМ)а разные Воиды, и тд ничего особенного не имеют!

**Comment by ark120202** [comment]
Our issue tracker isn't place for such issues. Use our VK group for this.
